name: Update Profile README

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write 
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install -g @octokit/rest
          npm install -g axios
          
      - name: Update GitHub Stats
        run: |
          # Create a simple script to update stats
          cat > update-stats.js << 'EOF'
          const fs = require('fs');
          const path = require('path');
          
          // Read current README
          const readmePath = path.join(process.cwd(), 'README.md');
          let readmeContent = fs.readFileSync(readmePath, 'utf8');
          
          // Update timestamp
          const now = new Date().toLocaleString('en-US', {
            timeZone: 'Asia/Kolkata',
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
          });
          
          // Add last updated timestamp
          if (readmeContent.includes('Last updated:')) {
            readmeContent = readmeContent.replace(
              /Last updated:.*/,
              `Last updated: ${now} IST`
            );
          } else {
            // Add timestamp at the end
            readmeContent += `\n\n---\n\n<div align="center">\n  <i>Last updated: ${now} IST</i>\n</div>`;
          }
          
          // Write back to README
          fs.writeFileSync(readmePath, readmeContent);
          console.log('README updated with timestamp');
          EOF
          
          node update-stats.js
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "🔄 Auto-update profile stats - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
          
      - name: Update Profile Views Badge
        run: |
          # This step ensures the profile views badge gets updated
          echo "Profile views badge will be updated automatically by the badge service"
          
      - name: Generate Activity Summary
        run: |
          # Create a summary of recent activity
          cat > activity-summary.md << 'EOF'
          # Recent Activity Summary
          
          ## Last 7 Days Activity
          - Profile views: Updated automatically
          - GitHub stats: Refreshed
          - Contribution graph: Updated
          
          ## Next Update
          - Scheduled for tomorrow at 00:00 UTC
          - Manual trigger available via GitHub Actions
          EOF
          
          echo "Activity summary generated"
